//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using IATA.AIDX.Common.FlightLegNotifRQ;
using IATA.AIDX.Common.FlightLegTypes;

namespace IATA.AIDX.Messages
{
    public interface IIATA_AIDX_FlightLegNotifRQ : IAIDX_FlightLegMessage
    {
        string CodeContext { get; set; }
        IATA_AIDX_FlightLegNotifRQDeliveringSystem DeliveringSystem { get; set; }
        FlightLegType[] FlightLeg { get; set; }
        IATA_AIDX_FlightLegNotifRQOriginator Originator { get; set; }
        IATA_AIDX_FlightLegNotifRQTarget Target { get; set; }
        IATA_AIDX_FlightLegNotifRQTransactionStatusCode TransactionStatusCode { get; set; }
    }

}
