//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using IATA.AIDX.Common.FlightLegRQ;

namespace IATA.AIDX.Messages
{
    public interface IIATA_AIDX_FlightLegRQ : IAIDX_FlightLegMessage
    {
        IATA_AIDX_FlightLegRQAirline Airline { get; set; }
        IATA_AIDX_FlightLegRQTarget Target { get; set; }
        IATA_AIDX_FlightLegRQTransactionStatusCode TransactionStatusCode { get; set; }

    }
}